### ISSUE TITLE
code problem 

### ISSUE THREAD

**Issue by panxpx** [razor08/Efficient-CNN-BiLSTM-for-Network-IDS#2]
your code  miss some part in nsl_kdd, can  you upgrade it?

**Comment by jayxsinha** [comment]
The code in this repository for NSL KDD is for multiclass classification, you can convert it to binary using a few simple steps. 
If you feel like there is some specific part of code missing in the repo, please respond with that.

**Comment by panxpx** [comment]
you know, the result  show  that x is not defined , may be you miss this part?

**Comment by panxpx** [comment]
By the way ,you  repository have code for binary  classification

**Comment by jayxsinha** [comment]
x is not defined error was in NSL KDD notebook which was actually extraneous cells that were never removed but have been removed now.

Also, there are 2 notebooks in the repo, both of them have multiclass classification done on NSL KDD and UNSW NB-15. 

Hope this helps clear up the issue.
