### ISSUE TITLE
 TypeError: ('Keyword argument not understood:', 'pool_length')

### ISSUE THREAD

**Issue by zeeno95** [razor08/Efficient-CNN-BiLSTM-for-Network-IDS#3]
how to fix this error: TypeError: ('Keyword argument not understood:', 'pool_length')

**Comment by jayxsinha** [comment]
Try using an earlier version of Keras. These errors in the way layers are defined are mostly due to dependency on specific Keras version or you can choose to modify the code to incorporate recent versions of Keras.

Hope this helps.

Thanks/
