### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shreeya-jain** [razor08/Efficient-CNN-BiLSTM-for-Network-IDS#5]
<img width="776" alt="p" src="https://user-images.githubusercontent.com/48252758/145705429-b2f1c6f1-2efa-46da-8a82-42b0e03d34f6.png">

ypeError                                 Traceback (most recent call last)
<ipython-input-59-fad498344778> in <module>()
     29 
     30 
---> 31     model.fit(x_train_1, y_train_1,validation_data=(x_test_2,y_test_2), epochs=2)
     32 
     33     pred = model.predict(x_test_2)

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    940       # In this case we have created variables on the first call, so we run the
    941       # defunned version which is guaranteed to never create variables.
--> 942       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    943     elif self._stateful_fn is not None:
    944       # Release the lock early so that multiple threads can perform the call

TypeError: 'NoneType' object is not callable

**Comment by jayxsinha** [comment]
Hi 

Have a look at the readme of the repo, I have added URLs to public Kaggle notebooks that will help you reproduce the results. 

Thanks!
