### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by furycurry** [razor08/Efficient-CNN-BiLSTM-for-Network-IDS#7]
I have been trying to run the program using UNSW-NB15 data set downloaded from the official site, but unfortunately I am stuck here(in the screenshot provided below). Can you kindly help me to figure it out? @razor08 
![image](https://user-images.githubusercontent.com/58500422/159928974-2cb31765-506e-45dc-bd57-c7609c51c433.png)

**Comment by jayxsinha** [comment]
From the looks of it, Pandas is not able to view the file that you have referred in pd.read_csv,  I would recommend going through the following: https://datatofish.com/import-csv-file-python-using-pandas/ 

I am closing the issue.
